import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  tutorialSidebar: [
    "home",
    {
      type: "category",
      label: "Golang - basic",
      items: [
        "tutorial-go/go_01_overview",
        "tutorial-go/go_02_setup_environment",
        "tutorial-go/go_03_variable_data_type",
        "tutorial-go/go_05_Function",
        "tutorial-go/go_06_Class_Method_Interface",
        "tutorial-go/go_07_Concurrentcy",
        "tutorial-go/go_08_Dependency",
      ],
    },
  ],
};

export default sidebars;
